services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=crm'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: