spring:

  # db config
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/crm

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
